projetoFrancisco/controllers/BlocosController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use yii;

class BlocosController extends Controller{
    public function actionListarBlocos(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        //$query = BlocosModel::find();
        $blTable = BlocosModel::tableName();
        $condTable = CondominiosModel::tableName();
        $query = (new \yii\db\Query())
        ->select(
            'bl.id, 
            bl.nomeBloco,
            bl.andares, 
            bl.unidadesAndar, 
            cond.nomeCondominio, 
            bl.idCondominio'

        )
        ->from($blTable.' bl')
        ->innerJoin($condTable.' cond', 'cond.id = bl.idCondominio');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $blocos = $query->orderBy('nomeBloco')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-blocos',[
            'blocos' => $blocos,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastrarBlocos(){
        return $this->render('cadastrar-blocos');
    }

    public function actionRealizaCadastroBloco(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/listar-blocos']);
        }
        return $this->render('cadastrar-blocos');
    }

    public static function listaBlocosSelect(){
        $query = BlocosModel::find();

        return $query->orderBy('nomeBloco')->all();
    }

    public static function novolistaBlocosSelect($from){
        $query = BlocosModel::find();
        $data = $query->where(['idCondominio' => $from])->orderBy('nomeBloco')->all();
        return $data;
    }

    public function actionListBlocosApi(){
        $request = \yii::$app->request;
        $query=BlocosModel::find();
        $data = $query->where(['idCondominio' => $request->post()])->orderBy('nomeBloco')->all();

        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nomeBloco'] = $d['nomeBloco'];
            $i++;
        }
        return json_encode($dados);
    }
    public function actionEditarBlocos(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = BlocosModel::find();
            $blocos = $query->where(['id' =>$request->get()])->one();
        }
        return $this->render('editar-blocos',[
        'edit' => $blocos
        ]);
      }
  
      public function actionRealizaEdicaoBloco(){
  
          $request = \yii::$app->request;
          if($request->isPost){
  
              $model = BlocosModel::findOne($request->post('id'));
              $model->attributes = $request->post();
              
              if($model->update()){
                  return $this->redirect(['blocos/listar-blocos']);
              }else{
                  return $this->redirect(['blocos/listar-blocos', 'msg' => 'erro']);
              }
          }
    }

    public function actionDeletaBloco(){
        
        try {
            $request = \yii::$app->request;
            $model = BlocosModel::findOne($request->get('id'));
            if($request->isGet){
                $model->delete();
            }
            return $this->redirect(['blocos/listar-blocos', 
                'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro deletado.',
                    'redir' => 'blocos/listar-blocos'
                ]
            ]);
        
        } catch (\Throwable $error) {
            return $this->redirect(['blocos/listar-blocos', 
                'myAlert' => 
                [
                    'type' => 'danger', 
                    'msg' => 'Não foi possível deletar o registro',
                    'redir' => 'blocos/listar-blocos'
                ]
            ]);  
        }

    }
}
?>

projetoFrancisco/views/blocos/cadastrar-blocos.php
<?
use yii\helpers\Url;
use app\controllers\CondominiosController;
?>

<h1>Cadastra blocos</h1>
<form method="post" id="cadastroBloco" action="<?= Url::to(['blocos/realiza-cadastro-bloco']);?>">
    <div class="form-row">

        <div class="col-sm-6 form-group">
            <label for="nome">Bloco</label>
            <input class="form-control" type="text" name="nomeBloco" value="" required>
        </div>
        
        <div class="col-sm-6 form-group">
            <label for="cnpj">Andares</label>
            <input class="form-control" type="text" name="andares" value="" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="cnpj">Unid. por Andar</label>
            <input class="form-control" type="text" name="unidadesAndar" value="" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="idCondominio">Condomínio</label>
            <select name="idCondominio" class="custom-select">
                <? 
                foreach(CondominiosController::listaCondominiosSelect() as $adm){?>
                <option value="<?=$adm['id']?>"><?=$adm['nomeCondominio']?></option>
                <? } ?>
            </select>
        </div>

        <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" value="<?= \yii::$app->request->csrfToken; ?>">

        <div class="col-sm-12">
            <button type="submit" class="btn btn-info buttonEnviar">Enviar</button>
        </div>
    </div>
</form>

projetoFrancisco/views/blocos/editar-blocos.php
<?

use app\components\selectedComponents;
use yii\helpers\Url;
use app\controllers\CondominiosController;
?>

<h1>Editar blocos</h1>
<form method="post" id="cadastroBloco" action="<?= Url::to(['blocos/realiza-edicao-bloco']);?>">
    <div class="form-row">

        <div class="col-sm-6 form-group">
            <label for="nome">Bloco</label>
            <input class="form-control" type="text" name="nomeBloco" value="<?=$edit['nomeBloco']?>" required>
        </div>
        
        <div class="col-sm-6 form-group">
            <label for="cnpj">Andares</label>
            <input class="form-control" type="text" name="andares" value="<?=$edit['andares']?>" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="cnpj">Unid. por Andar</label>
            <input class="form-control" type="text" name="unidadesAndar" value="<?=$edit['unidadesAndar']?>" required>
        </div>

        <div class="col-sm-4 form-group">
            <label for="idCondominio">Condomínio</label>
            <select name="idCondominio" class="custom-select">
                <? 
                foreach(CondominiosController::listaCondominiosSelect($edit['idCondominio']) as $und){
                echo '<option value="'.$und['id'].'"'.selectedComponents::isSelected($und['id'], $edit['id']).'>'.$und['nomeCondominio'].'</option>';
            }?>
            </select> 

        </div>

        <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" value="<?= \yii::$app->request->csrfToken; ?>">
        
        <input type="hidden" name="id" value="<?=$edit['id']?>">
        
        <div class="col-sm-12">
            <button type="submit" class="btn btn-info buttonEnviar">Enviar</button>
        </div>
    </div>
</form>

projetoFrancisco/views/blocos/listar-blocos.php
<?

use app\components\alertComponents;
use app\components\modalComponents;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$url_site = Url::base($schema = true);

if(isset($_GET['msg'])){
    echo alertComponents::myAlert('danger','Erro na requisição');
}
?>
<h1>Blocos</h1>

<table class="col col-12 table table-striped mt-5" id="listaBlocos">
    <tr>
        <td>Nome</td>
        <td>Andares</td>
        <td>Unid. Andar</td>
        <td>Condominio</td>
        <td align="center"><a href="index.php?r=blocos/cadastrar-blocos" class="btn btn-primary btn-sm">ADICIONAR</a></td>
    </tr>
    <? foreach ($blocos as $dados) {?>
        <tr data-id="<?=$dados['id']?>">
            <td><?= $dados['nomeBloco'] ?></td>
            <td><?= $dados['andares'] ?></td>
            <td><?= $dados['unidadesAndar'] ?></td>
            <td><?= $dados['nomeCondominio'] ?></td>
            <td align="center">
            <a href="index.php?r=blocos/editar-blocos&id=<?=$dados['id']?>" class="openModal"><i class="bi bi-pencil-square"></i></a>
            <a href="<?=$url_site?>/index.php?r=blocos/deleta-bloco&id=<?=$dados['id']?>" <i class="bi bi-trash-fill"></i></a>
            </td>
        </tr>
        <? } ?>
        
    </table>

    <?= LinkPager::widget([
        'pagination' => $paginacao,
        'linkContainerOptions' => [
            'class' => 'page-item'
        ],
        'linkOptions' =>[
            'class' => 'page-link'
        ],
        'disabledListItemSubTagOptions' => [
            'class' => 'pagelink'
        ]
    ])?>

    <div class="row">
        <div class="totalRegistros col-sm-6">Total Registros <?=$paginacao->totalCount?></div>
    </div>

    <?=modalComponents::initModal();?>