projetoFrancisco/controllers/UnidadesController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\UnidadesModel;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use yii;

class UnidadesController extends Controller{
    public function actionListarUnidades(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        //$query = UnidadesModel::find();
        $uniTable = UnidadesModel::tableName();
        $blTable = BlocosModel::tableName();
        $condTable = CondominiosModel::tableName();
        $query = (new \yii\db\Query())
        ->select(
        'uni.id, 
        uni.numeroUnidade, 
        uni.metragem,
        uni.vagasGaragem, 
        bl.nomeBloco, 
        cond.nomeCondominio, 
        uni.idBloco, 
        uni.idCondominio'
        )

        ->from($uniTable.' uni')
        ->innerJoin($condTable.' cond', 'cond.id = uni.idCondominio')
        ->innerJoin($blTable. ' bl', 'bl.id = uni.idBloco');


        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $unidades = $query->orderBy('numeroUnidade')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-unidades',[
            'unidades' => $unidades,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastrarUnidades(){
        return $this->render('cadastrar-unidades');
    }

    public function actionRealizaCadastroUnidade(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new UnidadesModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['unidades/listar-unidades']);
        }
        return $this->render('cadastrar-unidades');
    }

    public static function listaUnidadesSelect(){
        $query = UnidadesModel::find();

        return $query->orderBy('numeroUnidade')->all();
    }
    public function actionListUnidadesApi(){
        $request = \yii::$app->request;
        $query=UnidadesModel::find();
        $data = $query->where(['idBloco' => $request->post()])->orderBy('numeroUnidade')->all();

        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['numeroUnidade'] = $d['numeroUnidade'];
            $i++;
        }
        return json_encode($dados);
    }

    public function actionEditarUnidades(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = UnidadesModel::find();
            $unidades = $query->where(['id' =>$request->get()])->one();
        }
        return $this->render('editar-unidades',[
        'edit' => $unidades
        ]);
      }
  
    public function actionRealizaEdicaoUnidade(){
  
          $request = \yii::$app->request;
          if($request->isPost){
  
              $model = UnidadesModel::findOne($request->post('id'));
              $model->attributes = $request->post();
              
              if($model->update()){
                  return $this->redirect(['unidades/listar-unidades',
                  'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro editado com sucesso.',
                    'redir' => 'unidades/listar-unidades']
                ]);
              }else{
                  return $this->redirect(['unidades/listar-unidades', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaUnidade(){
        
        try {
            $request = \yii::$app->request;
            $model = UnidadesModel::findOne($request->get('id'));
            if($request->isGet){
                $model->delete();
            }
            return $this->redirect(['unidades/listar-unidades', 
                'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro deletado.',
                    'redir' => 'unidades/listar-unidades'
                ]
            ]);
        
        } catch (\Throwable $error) {
            return $this->redirect(['unidades/listar-unidades', 
                'myAlert' => 
                [
                    'type' => 'danger', 
                    'msg' => 'Não foi possível deletar o registro',
                    'redir' => 'unidades/listar-unidades'
                ]
            ]);  
        }

    }
}
?>

projetoFrancisco/views/unidades/cadastrar-unidades.php
<?
use yii\helpers\Url;
use app\controllers\CondominiosController;
use app\controllers\BlocosController;
?>

<h1>Cadastra Unidades</h1>
<form method="post" id="cadastroUnidade" action="<?= Url::to(['unidades/realiza-cadastro-unidade']);?>">
    <div class="form-row">

        <div class="col-sm-6 form-group">
            <label for="nome">Número unidade</label>
            <input class="form-control" type="text" name="numeroUnidade" value="" required>
        </div>
        
        <div class="col-sm-6 form-group">
            <label for="cnpj">Metragem</label>
            <input class="form-control" type="text" name="metragem" value="" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="cnpj">Unid. por Andar</label>
            <input class="form-control" type="text" name="unidadesAndar" value="" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="cnpj">Vagas garagem</label>
            <input class="form-control" type="text" name="vagasGaragem" value="" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="idCondominio">Condomínio</label>
            <select name="idCondominio" class="custom-select idCondominio">
                <? 
                foreach(CondominiosController::listaCondominiosSelect() as $adm){?>
                <option value="<?=$adm['id']?>"><?=$adm['nomeCondominio']?></option>
                <? } ?>
            </select>
        </div>

        <div class="col-sm-6 form-group">
            <label for="idBloco">Blocos</label>
            <select name="idBloco" class="custom-select">
                <? 
                foreach(BlocosController::listaBlocosSelect() as $adm){?>
                <option value="<?=$adm['id']?>"><?=$adm['nomeBloco']?></option>
                <? } ?>
            </select>
        </div>

        <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" value="<?= \yii::$app->request->csrfToken; ?>">

        <div class="col-sm-12">
            <button type="submit" class="btn btn-info buttonEnviar">Enviar</button>
        </div>
    </div>
</form>

projetoFrancisco/views/unidades/editar-unidades.php
<?

use app\components\selectedComponents;
use yii\helpers\Url;
use app\controllers\CondominiosController;
use app\controllers\BlocosController;
?>

<h1>Editar Unidades</h1>
<form method="post" id="cadastroUnidade" action="<?= Url::to(['unidades/realiza-edicao-unidade']);?>">
    <div class="form-row">

        <div class="col-sm-6 form-group">
            <label for="nome">Número unidade</label>
            <input class="form-control" type="text" name="numeroUnidade" value="<?=$edit['numeroUnidade']?>" required>
        </div>
        
        <div class="col-sm-6 form-group">
            <label for="cnpj">Metragem</label>
            <input class="form-control" type="text" name="metragem" value="<?=$edit['metragem']?>" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="cnpj">Vagas garagem</label>
            <input class="form-control" type="text" name="vagasGaragem" value="<?=$edit['vagasGaragem']?>" required>
        </div>

        <div class="col-sm-4 form-group">
            <label for="idCondominio">Condomínio</label>
            <select name="idCondominio" class="custom-select">
                <? 
                foreach(CondominiosController::listaCondominiosSelect($edit['idCondominio']) as $und){
                echo '<option value="'.$und['id'].'"'.selectedComponents::isSelected($und['id'], $edit['id']).'>'.$und['nomeCondominio'].'</option>';
            }?>
            </select> 

        </div>


        <div class="col-sm-4 form-group">
            <label for="idCondominio">Condomínio</label>
            <select name="idCondominio" class="custom-select">
                <? 
                foreach(BlocosController::listaBlocosSelect($edit['idBloco']) as $blc){
                echo '<option value="'.$blc['id'].'"'.selectedComponents::isSelected($blc['id'], $edit['id']).'>'.$blc['nomeBloco'].'</option>';
            }?>
            </select> 

        </div>

        <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" value="<?= \yii::$app->request->csrfToken; ?>">

        <input type="hidden" name="id" value="<?=$edit['id']?>">

        <div class="col-sm-12">
            <button type="submit" class="btn btn-info buttonEnviar">Enviar</button>
        </div>
    </div>
</form>

projetoFrancisco/views/unidades/listar-unidades.php
<?

use app\components\alertComponents;
use app\components\modalComponents;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$url_site = Url::base($schema = true);

if(isset($_GET['msg'])){
    echo alertComponents::myAlert('danger','Erro na requisição');
}

?>
<h1>Unidades</h1>

<table class="col col-12 table table-striped mt-5" id="listaUnidades">
    <tr>
        <td>Nome</td>
        <td>Metragem</td>
        <td>Vagas Garagem</td>
        <td>Bloco</td>
        <td>Condomínio</td>
        <td align="center"><a href="index.php?r=unidades/cadastrar-unidades" class="btn btn-primary btn-sm">ADICIONAR</a></td>
    </tr>
    <? foreach ($unidades as $dados) {?>
        <tr data-id="<?=$dados['id']?>">
            <td><?= $dados['numeroUnidade'] ?></td>
            <td><?= $dados['metragem'] ?></td>
            <td><?= $dados['vagasGaragem'] ?></td>
            <td><?= $dados['nomeBloco'] ?></td>
            <td><?= $dados['nomeCondominio'] ?></td>
            <td align="center">
            <a href="index.php?r=unidades/editar-unidades&id=<?=$dados['id']?>" class="openModal"><i class="bi bi-pencil-square"></i></a>
            <a href="<?=$url_site?>/index.php?r=unidades/deleta-unidade&id=<?=$dados['id']?>" <i class="bi bi-trash-fill"></i></a>
            </td>
        </tr>
        <? } ?>
        
    </table>

    <?= LinkPager::widget([
        'pagination' => $paginacao,
        'linkContainerOptions' => [
            'class' => 'page-item'
        ],
        'linkOptions' =>[
            'class' => 'page-link'
        ],
        'disabledListItemSubTagOptions' => [
            'class' => 'pagelink'
        ]
    ])?>

    <div class="row">
        <div class="totalRegistros col-sm-6">Total Registros <?=$paginacao->totalCount?></div>
    </div>
    <?=modalComponents::initModal();?>