projetoFrancisco/controllers/BlocosController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use yii;

class BlocosController extends Controller{
    public function actionListarBlocos(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        //$query = BlocosModel::find();
        $blTable = BlocosModel::tableName();
        $condTable = CondominiosModel::tableName();
        $query = (new \yii\db\Query())
        ->select(
            'bl.id, 
            bl.nomeBloco,
            bl.andares, 
            bl.unidadesAndar, 
            cond.nomeCondominio, 
            bl.idCondominio'

        )
        ->from($blTable.' bl')
        ->innerJoin($condTable.' cond', 'cond.id = bl.idCondominio');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $blocos = $query->orderBy('nomeBloco')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-blocos',[
            'blocos' => $blocos,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastrarBlocos(){
        return $this->render('cadastrar-blocos');
    }

    public function actionRealizaCadastroBloco(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/listar-blocos']);
        }
        return $this->render('cadastrar-blocos');
    }

    public static function listaBlocosSelect(){
        $query = BlocosModel::find();

        return $query->orderBy('nomeBloco')->all();
    }

    public static function novolistaBlocosSelect($from){
        $query = BlocosModel::find();
        $data = $query->where(['idCondominio' => $from])->orderBy('nomeBloco')->all();
        return $data;
    }

    public function actionListBlocosApi(){
        $request = \yii::$app->request;
        $query=BlocosModel::find();
        $data = $query->where(['idCondominio' => $request->post()])->orderBy('nomeBloco')->all();

        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nomeBloco'] = $d['nomeBloco'];
            $i++;
        }
        return json_encode($dados);
    }
    public function actionEditarBlocos(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = BlocosModel::find();
            $blocos = $query->where(['id' =>$request->get()])->one();
        }
        return $this->render('editar-blocos',[
        'edit' => $blocos
        ]);
      }
  
      public function actionRealizaEdicaoBloco(){
  
          $request = \yii::$app->request;
          if($request->isPost){
  
              $model = BlocosModel::findOne($request->post('id'));
              $model->attributes = $request->post();
              
              if($model->update()){
                  return $this->redirect(['blocos/listar-blocos']);
              }else{
                  return $this->redirect(['blocos/listar-blocos', 'msg' => 'erro']);
              }
          }
    }

    public function actionDeletaBloco(){
        
        try {
            $request = \yii::$app->request;
            $model = BlocosModel::findOne($request->get('id'));
            if($request->isGet){
                $model->delete();
            }
            return $this->redirect(['blocos/listar-blocos', 
                'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro deletado.',
                    'redir' => 'blocos/listar-blocos'
                ]
            ]);
        
        } catch (\Throwable $error) {
            return $this->redirect(['blocos/listar-blocos', 
                'myAlert' => 
                [
                    'type' => 'danger', 
                    'msg' => 'Não foi possível deletar o registro',
                    'redir' => 'blocos/listar-blocos'
                ]
            ]);  
        }

    }
}
?>

projetoFrancisco/controllers/ConselhosController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\ConselhosModel;
use yii;

class ConselhosController extends Controller{
    public function actionListarConselhos(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $query = ConselhosModel::find();

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $conselhos = $query->orderBy('nome')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-conselhos',[
            'conselhos' => $conselhos,
            'paginacao' => $paginacao,
        ]);
        
    }
    public function actionCadastrarConselhos(){
        return $this->render('cadastrar-conselhos');
    }

    public function actionRealizaCadastroConselho(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new ConselhosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['conselhos/listar-conselhos']);
        }
        return $this->render('cadastrar-conselhos');
    }

    public static function listaConselhossSelect(){
        $query = ConselhosModel::find();

        return $query->orderBy('nome')->all();
    }

    public function actionEditarConselhos(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = ConselhosModel::find();
            $conselhos = $query->where(['id' =>$request->get()])->one();
        }
        return $this->render('editar-conselhos',[
        'edit' => $conselhos
        ]);
      }
  
    public function actionRealizaEdicaoConselho(){
  
          $request = \yii::$app->request;
          if($request->isPost){
  
              $model = ConselhosModel::findOne($request->post('id'));
              $model->attributes = $request->post();
              
              if($model->update()){
                  return $this->redirect(['conselhos/listar-conselhos',
                  'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro editado com sucesso.',
                    'redir' => 'conselhos/listar-conselhos']
                ]);
              }else{
                  return $this->redirect(['conselhos/listar-conselhos', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaConselho(){
        
        try {
            $request = \yii::$app->request;
            $model = ConselhosModel::findOne($request->get('id'));
            if($request->isGet){
                $model->delete();
            }
            return $this->redirect(['conselhos/listar-conselhos', 
                'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro deletado.',
                    'redir' => 'conselhos/listar-conselhos'
                ]
            ]);
        
        } catch (\Throwable $error) {
            return $this->redirect(['conselhos/listar-conselhos', 
                'myAlert' => 
                [
                    'type' => 'danger', 
                    'msg' => 'Não foi possível deletar o registro',
                    'redir' => 'conselhos/listar-conselhos'
                ]
            ]);  
        }

    }
}
?>

projetoFrancisco/controllers/MoradoresController.php
<?
namespace app\controllers;

use app\components\alertComponents;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\MoradoresModel;
use app\models\UnidadesModel;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use yii;

class MoradoresController extends Controller{
    public function actionListarMoradores(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        //$query = MoradoresModel::find();
        $uniTable = UnidadesModel::tableName();
        $blTable = BlocosModel::tableName();
        $condTable = CondominiosModel::tableName();
        $moradorTable = MoradoresModel::tableName();
        $query = (new \yii\db\Query())
        ->select(
        'cad.id, 
        cad.nome, 
        cad.cpf, 
        cad.email, 
        cad.fone, 
        cad.dataCadastro, 
        cond.nomeCondominio, 
        bl.nomeBloco, 
        uni.numeroUnidade, 
        cad.idCondominio, 
        cad.idBloco, 
        cad.idUnidade,
        cad.dataUpdate,
        cad.dataCadastro'
        )

        ->from($moradorTable.' cad')
        ->innerJoin($uniTable.' uni', 'uni.id = cad.idUnidade')
        ->innerJoin($condTable.' cond', 'cond.id = uni.idCondominio')
        ->innerJoin($blTable. ' bl', 'bl.id = uni.idBloco');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $moradores = $query->orderBy('nome')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-moradores',[
            'moradores' => $moradores,
            'paginacao' => $paginacao,
        ]);
    }
    public function actionCadastrarMoradores(){
        return $this->render('cadastrar-moradores');
    }

    public function actionRealizaCadastroMorador(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new MoradoresModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['moradores/listar-moradores']);
        }
        return $this->render('cadastrar-moradores');
    }

    public function actionEditarMoradores(){
      $this->layout = false;
      $request = \yii::$app->request;
      if($request->isGet){
          $query = MoradoresModel::find();
          $moradores = $query->where(['id' =>$request->get()])->one();
      }
      return $this->render('editar-moradores',[
      'edit' => $moradores
      ]);
    }

    public function actionRealizaEdicaoMorador(){

        $request = \yii::$app->request;
        if($request->isPost){

            $model = MoradoresModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if($model->update()){
                return $this->redirect(['moradores/listar-moradores',
                'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro editado com sucesso.',
                    'redir' => 'moradores/listar-moradores']
            ]);
            }else{
                return $this->redirect(['moradores/listar-moradores', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaMorador(){
        
        try {
            $request = \yii::$app->request;
            $model = MoradoresModel::findOne($request->get('id'));
            if($request->isGet){
                $model->delete();
            }
            return $this->redirect(['moradores/listar-moradores', 
                'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro deletado.',
                    'redir' => 'moradores/listar-moradores'
                ]
            ]);
        
        } catch (\Throwable $error) {
            return $this->redirect(['moradores/listar-moradores', 
                'myAlert' => 
                [
                    'type' => 'danger', 
                    'msg' => 'Não foi possível deletar o registro',
                    'redir' => 'moradores/listar-moradores'
                ]
            ]);  
        }

    }

}
?>

projetoFrancisco/controllers/UnidadesController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\UnidadesModel;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use yii;

class UnidadesController extends Controller{
    public function actionListarUnidades(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        //$query = UnidadesModel::find();
        $uniTable = UnidadesModel::tableName();
        $blTable = BlocosModel::tableName();
        $condTable = CondominiosModel::tableName();
        $query = (new \yii\db\Query())
        ->select(
        'uni.id, 
        uni.numeroUnidade, 
        uni.metragem,
        uni.vagasGaragem, 
        bl.nomeBloco, 
        cond.nomeCondominio, 
        uni.idBloco, 
        uni.idCondominio'
        )

        ->from($uniTable.' uni')
        ->innerJoin($condTable.' cond', 'cond.id = uni.idCondominio')
        ->innerJoin($blTable. ' bl', 'bl.id = uni.idBloco');


        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $unidades = $query->orderBy('numeroUnidade')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-unidades',[
            'unidades' => $unidades,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastrarUnidades(){
        return $this->render('cadastrar-unidades');
    }

    public function actionRealizaCadastroUnidade(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new UnidadesModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['unidades/listar-unidades']);
        }
        return $this->render('cadastrar-unidades');
    }

    public static function listaUnidadesSelect(){
        $query = UnidadesModel::find();

        return $query->orderBy('numeroUnidade')->all();
    }
    public function actionListUnidadesApi(){
        $request = \yii::$app->request;
        $query=UnidadesModel::find();
        $data = $query->where(['idBloco' => $request->post()])->orderBy('numeroUnidade')->all();

        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['numeroUnidade'] = $d['numeroUnidade'];
            $i++;
        }
        return json_encode($dados);
    }

    public function actionEditarUnidades(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = UnidadesModel::find();
            $unidades = $query->where(['id' =>$request->get()])->one();
        }
        return $this->render('editar-unidades',[
        'edit' => $unidades
        ]);
      }
  
    public function actionRealizaEdicaoUnidade(){
  
          $request = \yii::$app->request;
          if($request->isPost){
  
              $model = UnidadesModel::findOne($request->post('id'));
              $model->attributes = $request->post();
              
              if($model->update()){
                  return $this->redirect(['unidades/listar-unidades',
                  'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro editado com sucesso.',
                    'redir' => 'unidades/listar-unidades']
                ]);
              }else{
                  return $this->redirect(['unidades/listar-unidades', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaUnidade(){
        
        try {
            $request = \yii::$app->request;
            $model = UnidadesModel::findOne($request->get('id'));
            if($request->isGet){
                $model->delete();
            }
            return $this->redirect(['unidades/listar-unidades', 
                'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro deletado.',
                    'redir' => 'unidades/listar-unidades'
                ]
            ]);
        
        } catch (\Throwable $error) {
            return $this->redirect(['unidades/listar-unidades', 
                'myAlert' => 
                [
                    'type' => 'danger', 
                    'msg' => 'Não foi possível deletar o registro',
                    'redir' => 'unidades/listar-unidades'
                ]
            ]);  
        }

    }
}
?>

projetoFrancisco/views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="img/logo.png" width="100px"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            [
                'label' => 'Administradoras',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['administradoras/listar-administradoras']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['administradoras/cadastrar-administradoras']
                    ]
                ]
            ],
            [
                'label' => 'Condominios',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['condominios/listar-condominios']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['condominios/cadastrar-condominios']
                    ]
                ]
            ],
            [
                'label' => 'Blocos',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['blocos/listar-blocos']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['blocos/cadastrar-blocos']
                    ]
                ]
            ],
            [
                'label' => 'Unidades',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['unidades/listar-unidades']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['unidades/cadastrar-unidades']
                    ]
                ]
            ],
            [
                'label' => 'Moradores',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['moradores/listar-moradores']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['moradores/cadastrar-moradores']
                    ]
                ]
            ],
            [
                'label' => 'Conselhos',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['conselhos/listar-conselhos']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['conselhos/cadastrar-conselhos']
                    ]
                ]
            ],
            [
                'label' => 'Patrimonios',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['patrimonios/listar-patrimonios']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['patrimonios/cadastrar-patrimonios']
                    ]
                ]
            ],
        Yii::$app->user->isGuest ? (
            ['label' => 'Login', 'url' => ['/site/login']]
        ) : (
            '<li>'
            . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->nome . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>'
        )    
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0 mt-5">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted bg-dark">
    <div class="container">
        <p class="float-left">&copy; AP Controle <?= date('Y') ?></p>
        <p class="float-right">Suporte (47)98899-8989</p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>