projetoFrancisco/controllers/PatrimoniosController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\PatrimoniosModel;
use app\models\CondominiosModel;
use yii;

class PatrimoniosController extends Controller{

    public function actionListarPatrimonios(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        //$query = MoradoresModel::find();
   
        $condTable = CondominiosModel::tableName();
        $patrimonioTable = PatrimoniosModel::tableName();
        $query = (new \yii\db\Query())
        ->select(
        'cad.id, 
        cad.descricao, 
        cad.data_aquisicao, 
        cad.quantidade, 
        cad.valor, 
        cad.documento,  
        cad.observacao,
        cond.nomeCondominio'
        )

        ->from($patrimonioTable.' cad')
        ->innerJoin($condTable.' cond', 'cond.id = cad.idCondominio');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $patrimonios = $query->orderBy('descricao')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-patrimonios',[
            'patrimonios' => $patrimonios,
            'paginacao' => $paginacao,
        ]);
    }

    public function actionCadastrarPatrimonios(){
        return $this->render('cadastrar-patrimonios');
    }

    public function actionRealizaCadastroPatrimonio(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new PatrimoniosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['patrimonios/listar-patrimonios']);
        }
        return $this->render('cadastrar-patrimonios');
    }

    public static function listaPatrimoniosSelect(){
        $query = PatrimoniosModel::find();

        return $query->orderBy('descricao')->all();
    }

    public function actionEditarPatrimonios(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = PatrimoniosModel::find();
            $patrimonios = $query->where(['id' =>$request->get()])->one();
        }
        return $this->render('editar-patrimonios',[
        'edit' => $patrimonios
        ]);
      }
  
      public function actionRealizaEdicaoPatrimonio(){
  
          $request = \yii::$app->request;
          if($request->isPost){
  
              $model = PatrimoniosModel::findOne($request->post('id'));
              $model->attributes = $request->post();
              
              if($model->update()){
                  return $this->redirect(['patrimonios/listar-patrimonios',
                  'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro editado com sucesso.',
                    'redir' => 'patrimonios/listar-patrimonios']
                ]);
              }else{
                  return $this->redirect(['patrimonios/listar-patrimonios', 'msg' => 'erro']);
              }
          }
      }

    public function actionDeletaPatrimonio(){
        
        try {
            $request = \yii::$app->request;
            $model = PatrimoniosModel::findOne($request->get('id'));
            if($request->isGet){
                $model->delete();
            }
            return $this->redirect(['patrimonios/listar-patrimonios', 
                'myAlert' => [
                    'type' => 'success', 
                    'msg' => 'Registro deletado.',
                    'redir' => 'patrimonios/listar-patrimonios'
                ]
            ]);
        
        } catch (\Throwable $error) {
            return $this->redirect(['patrimonios/listar-patrimonios', 
                'myAlert' => 
                [
                    'type' => 'danger', 
                    'msg' => 'Não foi possível deletar o registro',
                    'redir' => 'patrimonios/listar-patrimonios'
                ]
            ]);  
        }

    }

}
?>

projetoFrancisco/views/patrimonios/cadastrar-patrimonios.php
<?

use yii\helpers\Url;
use app\controllers\CondominiosController;
?>

<h1>Cadastrar Patrimônio</h1>
<form method="post" id="cadastroCondominio" action="<?echo Url::to(['patrimonios/realiza-cadastro-patrimonio']);?>">
    <div class="form-row">

        <div class="col-sm-6 form-group">
            <label for="idCondominio">Condominio</label>
            <select name="idCondominio" class="custom-select">
                <? 
                foreach(CondominiosController::listaCondominiosSelect() as $adm){?>
                <option value="<?=$adm['id']?>"><?=$adm['nomeCondominio']?></option>
                <? } ?>
            </select>
        </div>

        <div class="col-sm-6 form-group">
            <label for="descricao">Descrição</label>
            <input class="form-control" type="text" name="descricao" value="" required>
        </div>
        
        <div class="col-sm-6 form-group">
            <label for="data_aquisicao">Data Aquisição</label>
            <input class="form-control" type="date" name="data_aquisicao" value="" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="quantidade">Quantidade</label>
            <input class="form-control" type="text" name="quantidade" value="" required>
        </div>
        <div class="col-sm-6 form-group">
            <label for="valor">Valor</label>
            <input class="form-control" type="tel" name="valor" value="" required>
        </div>
        <div class="col-sm-6 form-group">
            <label for="documento">Documento</label>
            <input class="form-control" type="text" name="documento" value="" required>
        </div>
        <div class="col-12 col-md-12">
            <div class="form-group">
                <label for="">Observação</label>
                <textarea class="form-control" name="observacao" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
        </div>


        <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" value="<?= \yii::$app->request->csrfToken; ?>">

        <div class="col-sm-12">
            <button type="submit" class="btn btn-info buttonEnviar">Enviar</button>
        </div>
    </div>
</form>

projetoFrancisco/views/patrimonios/editar-patrimonios.php
<?

use yii\helpers\Url;
use app\controllers\CondominiosController;
use app\components\selectedComponents;

?>

<h1>Editar patrimônio</h1>
<form method="post" id="cadastroPatrimonio" action="<?echo Url::to(['patrimonios/realiza-edicao-patrimonio']);?>">
    <div class="form-row">

        <div class="col-sm-6 form-group">
            <label for="id">Patrimônio</label>
            <select name="id" class="custom-select">
                <? 
                foreach(CondominiosController::listaCondominiosSelect($edit['id']) as $adm){
                echo '<option value="'.$adm['id'].'"'.selectedComponents::isSelected($adm['id'], $edit['id']).'>'.$adm['nomeCondominio'].'</option>';
                } ?>
            </select>
        </div>

        <div class="col-sm-6 form-group">
            <label for="descricao">Descricao</label>
            <input class="form-control" type="text" name="descricao" value="<?=$edit['descricao']?>" required>
        </div>
        
        <div class="col-sm-6 form-group">
            <label for="data_aquisicao">Data Aquisição</label>
            <input class="form-control" type="text" name="data_aquisicao" value="<?=$edit['data_aquisicao']?>" required>
        </div>

        <div class="col-sm-6 form-group">
            <label for="quantidade">Quantidade</label>
            <input class="form-control" type="text" name="quantidade" value="<?=$edit['quantidade']?>" required>
        </div>
        <div class="col-sm-6 form-group">
            <label for="valor">Valor</label>
            <input class="form-control" type="text" name="valor" value="<?=$edit['valor']?>" required>
        </div>
        <div class="col-sm-6 form-group">
            <label for="documento">Documento</label>
            <input class="form-control" type="text" name="documento" value="<?=$edit['documento']?>" required>
        </div>
        <div class="col-sm-6 form-group">
            <label for="observacao">Observação</label>
            <input class="form-control" type="text" name="observacao" value="<?=$edit['observacao']?>" required>
        </div>


        <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" value="<?= \yii::$app->request->csrfToken; ?>">

        <div class="col-sm-12">
            <button type="submit" class="btn btn-info buttonEnviar">Enviar</button>
        </div>
    </div>
</form>

projetoFrancisco/views/patrimonios/listar-patrimonios.php
<?

use app\components\alertComponents;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\components\maskComponents;
use app\components\modalComponents;

$url_site = Url::base($schema = true);
if(isset($_GET['msg'])){
    echo alertComponents::myAlert('danger','Erro na requisição');
}

?>
<h1>Patrimônios</h1>

<table class="col col-12 table table-striped mt-5" id="listaPatrimonios">
    <tr>
        <td>Descrição</td>
        <td>Data aquisição</td>
        <td>Quantidade</td>
        <td>Valor</td>
        <td>Documento</td>
        <td>Observação</td>
        <td>Condominio</td>
        
        <td align="center"><a href="index.php?r=patrimonios/cadastrar-patrimonios" class="btn btn-primary btn-sm">ADICIONAR</a></td>
    </tr>
    <? foreach ($patrimonios as $dados) {?>
        <tr data-id="<?=$dados['id']?>">
            <td><?= $dados['descricao'] ?></td>
            <td><?= Yii::$app->formatter->format($dados['data_aquisicao'],'date') ?></td>
            <td><?= $dados['quantidade'] ?></td>
            <td><?= Yii::$app->formatter->asCurrency($dados['valor']) ?></td>
            <td><?= $dados['documento'] ?></td>
            <td><?= $dados['observacao'] ?></td>
            <td><?= $dados['nomeCondominio'] ?></td>
            
            <td align="center">
                <a href="index.php?r=patrimonios/editar-patrimonios&id=<?=$dados['id']?>" class="openModal"><i class="bi bi-pencil-square"></i></a>
                <a href="<?=$url_site?>/index.php?r=patrimonios/deleta-patrimonio&id=<?=$dados['id']?>" <i class="bi bi-trash-fill"></i></a>
            </td>
        </tr>
        <? } ?>
        
    </table>

    <?= LinkPager::widget([
        'pagination' => $paginacao,
        'linkContainerOptions' => [
            'class' => 'page-item'
        ],
        'linkOptions' =>[
            'class' => 'page-link'
        ],
        'disabledListItemSubTagOptions' => [
            'class' => 'pagelink'
        ]
    ])?>

    <div class="row">
        <div class="totalRegistros col-sm-6">Total Registros <?=$paginacao->totalCount?></div>
    </div>
    <?=modalComponents::initModal();?>